#include "Event.h"

/*
GVK_KEY_A, GVK_KEY_B, GVK_KEY_C, GVK_KEY_D, GVK_KEY_E, GVK_KEY_F, GVK_KEY_G, GVK_KEY_H,
GVK_KEY_I, GVK_KEY_J, GVK_KEY_K, GVK_KEY_L, GVK_KEY_M, GVK_KEY_N, GVK_KEY_O, GVK_KEY_P,
GVK_KEY_Q, GVK_KEY_R, GVK_KEY_S, GVK_KEY_T, GVK_KEY_U, GVK_KEY_V, GVK_KEY_W, GVK_KEY_X,
GVK_KEY_Y, GVK_KEY_Z,
GVK_KEY_1, GVK_KEY_2, GVK_KEY_3, GVK_KEY_4, GVK_KEY_5, GVK_KEY_6, GVK_KEY_7, GVK_KEY_8,
GVK_KEY_9, GVK_KEY_0,
GVK_MOUSE_1, GVK_MOUSE_2, GVK_MOUSE_3,
GVK_KEY_SPACE, GVK_KEY_SHIFT, GVK_KEY_ESCAPE, GVK_KEY_ENTER, GVK_KEY_TAB, GVK_KEY_BACKSPACE, GVK_KEY_PRINTSCREEN, GVK_KEY_CONTROL,
GVK_KEY_RIGHT, GVK_KEY_LEFT, GVK_KEY_DOWN, GVK_KEY_UP,
GVK_KEY_NUM
*/
std::vector<std::string> kbs::g_keyCodeStringTable = { "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q",
"R","S","T","U","V","W","X","Y","Z","1","2","3","4","5","6","7","8","9","0", "MOUSE_1","MOUSE_2","MOUSE_3","SPACE","SHIFT", "ESCAPE","ENTER",
"TAB","BACKSPACE","PRINT_SCREEN","CONTROL","RIGHT","LEFT","DOWN","UP","","","","","","",""};